[2024-02-20T12:24:51.335+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdag3.tsk1 manual__2024-02-20T12:24:50.685958+00:00 [queued]>
[2024-02-20T12:24:51.340+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdag3.tsk1 manual__2024-02-20T12:24:50.685958+00:00 [queued]>
[2024-02-20T12:24:51.340+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-02-20T12:24:51.340+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-02-20T12:24:51.340+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-02-20T12:24:51.348+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk1> on 2024-02-20 12:24:50.685958+00:00
[2024-02-20T12:24:51.351+0000] {standard_task_runner.py:55} INFO - Started process 169 to run task
[2024-02-20T12:24:51.353+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'triggerdag3', 'tsk1', 'manual__2024-02-20T12:24:50.685958+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/triggerdag3.py', '--cfg-path', '/tmp/tmpdywhadv7']
[2024-02-20T12:24:51.353+0000] {standard_task_runner.py:83} INFO - Job 93: Subtask tsk1
[2024-02-20T12:24:51.385+0000] {task_command.py:388} INFO - Running <TaskInstance: triggerdag3.tsk1 manual__2024-02-20T12:24:50.685958+00:00 [running]> on host d405f097ba80
[2024-02-20T12:24:51.422+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=triggerdag3
AIRFLOW_CTX_TASK_ID=tsk1
AIRFLOW_CTX_EXECUTION_DATE=2024-02-20T12:24:50.685958+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-20T12:24:50.685958+00:00
[2024-02-20T12:24:51.422+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-02-20T12:24:51.423+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-02-20T12:24:51.429+0000] {subprocess.py:86} INFO - Output:
[2024-02-20T12:24:51.430+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-02-20T12:24:51.435+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-02-20T12:24:51.438+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=triggerdag3, task_id=tsk1, execution_date=20240220T122450, start_date=20240220T122451, end_date=20240220T122451
[2024-02-20T12:24:51.445+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 93 for task tsk1 (Bash command failed. The command returned a non-zero exit code 1.; 169)
[2024-02-20T12:24:51.484+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-02-20T12:24:51.499+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
